import '../styles/global.css';
import { ReactNode } from 'react';
import AuthProvider from './AuthProvider'; // a wrapper Client Component

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
